import type { Metadata } from "next";
import Script from "next/script";
import "@fontsource/noto-serif-sc/400.css";
import "@fontsource/noto-serif-sc/500.css";
import "@fontsource/noto-serif-sc/600.css";
import "@fontsource/noto-serif-sc/700.css";
import "./globals.css";

const themeLanguageInitScript = `(function(){try{var theme=localStorage.getItem('theme');if(theme==='dark'){document.documentElement.classList.add('dark');}var language=localStorage.getItem('language')==='zh'?'zh':'en';document.documentElement.dataset.language=language;document.documentElement.lang=language==='zh'?'zh-CN':'en';}catch(e){}})();`;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col">
        <Script
          id="theme-language-init"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: themeLanguageInitScript }}
        />
        <span
          id="font-debug-zh"
          data-font-debug
          aria-hidden="true"
          style={{
            position: "absolute",
            width: 1,
            height: 1,
            overflow: "hidden",
            clipPath: "inset(50%)",
            whiteSpace: "nowrap",
            fontFamily: '"Noto Serif SC", "Source Han Serif SC", "Songti SC", serif',
          }}
        >
          中文字体测试：人工智能 后端开发 项目经历
        </span>
        {children}
      </body>
    </html>
  );
}



